-- Strict staff password management. Run after upgrade.sql.
-- Supabase's admin API updates password and app_metadata in the same transaction.
-- Defer the check to transaction end so it sees BOTH changes. Ordinary users
-- cannot change app_metadata, including through the direct Auth API.
-- Validate against the hosted Auth version with a disposable staff account
-- before admitting the team. Provider-side password rehashing also hits this
-- guard: revisit it when changing Auth hashing configuration.
begin;
create or replace function public.enforce_managed_staff_password() returns trigger
language plpgsql security definer set search_path = public as $$
declare final_nonce text;
begin
  if old.encrypted_password is not distinct from new.encrypted_password then return null; end if;
  if not exists(select 1 from public.users where id=new.id) then return null; end if;
  select raw_app_meta_data->>'staff_password_change' into final_nonce from auth.users where id=new.id;
  if final_nonce is null or final_nonce = coalesce(old.raw_app_meta_data->>'staff_password_change','') then
    raise exception 'Staff passwords must be generated by the church administrator';
  end if;
  return null;
end $$;
revoke all on function public.enforce_managed_staff_password() from public, anon, authenticated;
drop trigger if exists managed_staff_password on auth.users;
create constraint trigger managed_staff_password after update on auth.users
deferrable initially deferred for each row execute function public.enforce_managed_staff_password();
commit;
-- Emergency rollback for an incompatible Auth upgrade (SQL editor only):
-- DROP TRIGGER managed_staff_password ON auth.users;
