import {supabase} from '../../shared/supabase.js';
import {initProtectedPage,readAllRows,escapeHtml as e,setMessage,subscribeTables} from './auth.js';
const $=id=>document.getElementById(id);let dirty=false;document.addEventListener('input',event=>{if(event.target.closest('[data-care]'))dirty=true;});let profile,people=[],events=[],staff=[],requests=[];
$('journeyMonth').value=new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Johannesburg',year:'numeric',month:'2-digit'}).format(new Date()).slice(0,7);
const leader=()=>['super_admin','admin','coordinator','pastor'].includes(profile.role);
const link=p=>`<a href="person.html?id=${p.person_id}">${e(p.full_name)}</a>`;
function render(){
 $("journeyOverview").classList.toggle("hidden",!leader());
 const month=$('journeyMonth').value,selected=events.filter(x=>x.occurred_on.startsWith(month));
 const count=kind=>new Set(selected.filter(x=>x.kind===kind).map(x=>x.person_id)).size;
 const delays=[];for(const first of selected.filter(x=>x.kind==='first_visit')){const call=events.filter(x=>x.person_id===first.person_id&&x.kind==='call'&&x.occurred_on>=first.occurred_on).sort((a,b)=>a.occurred_on.localeCompare(b.occurred_on))[0];if(call)delays.push((Date.parse(call.occurred_on)-Date.parse(first.occurred_on))/86400000);}
 const metrics=[['First-time visitors',count('first_visit')],['Returned visitors',count('return_visit')],['Started discipleship',count('discipleship_started')],['Completed discipleship',count('discipleship_completed')],['Awaiting first contact',people.filter(p=>p.status==='not_called').length],['Average days to successful contact',delays.length?(delays.reduce((a,b)=>a+b,0)/delays.length).toFixed(1)+' ('+delays.length+' recorded)':'No recorded dates']];
 $('journeySummary').innerHTML=metrics.map(([label,n])=>`<article class="summary-pill"><strong>${n}</strong><div>${label}</div></article>`).join('');
 const namesFor=(kind)=>people.filter(p=>selected.some(x=>x.person_id===p.person_id&&x.kind===kind)).map(link).join(' · ')||'<p>None recorded for this month.</p>';
 const classMembers=people.filter(p=>events.some(x=>x.person_id===p.person_id&&x.kind==='discipleship_started')&&!events.some(x=>x.person_id===p.person_id&&x.kind==='discipleship_completed'));
 const interested=people.filter(p=>/^(yes|interested|true)/i.test(p.membership_interest||'')||events.some(x=>x.person_id===p.person_id&&x.kind==='membership_interest'));
 $('journeyPeople').innerHTML=`<h3>First-time visitors this month</h3>${namesFor("first_visit")}<h3>Who returned this month</h3>${namesFor("return_visit")}<h3>Currently in discipleship (${classMembers.length})</h3>${classMembers.map(link).join(" · ")||"<p>No class starts recorded yet.</p>"}<h3>Membership interest (${interested.length})</h3>${interested.map(link).join(' · ')||'<p>None recorded yet.</p>'}<h3>Needs follow-up (${people.filter(p=>!['completed','not_interested'].includes(p.status)).length})</h3>${people.filter(p=>!['completed','not_interested'].includes(p.status)).map(link).join(' · ')||'<p>No open follow-ups.</p>'}`;
 $('assignmentPanel').classList.toggle('hidden',!leader());
 $('assignmentWorkers').innerHTML=staff.filter(s=>s.role==='team'&&s.is_active).map(s=>`<label class="staff-toggle"><input type="checkbox" data-worker="${s.id}" ${s.available_for_assignment?'checked':''}> ${e(s.name)} — ${people.filter(p=>p.assigned_to===s.id&&!['completed','not_interested'].includes(p.status)).length} open</label>`).join('')||'<p>No active follow-up workers.</p>';
 $('assignmentWorkers').querySelectorAll('[data-worker]').forEach(input=>input.onchange=async()=>{input.disabled=true;try{const {error}=await supabase.rpc('set_assignment_availability',{p_user:input.dataset.worker,p_available:input.checked});if(error)throw error;await load();}catch(err){setMessage($('ministryMessage'),err.message,'error');input.checked=!input.checked;}finally{input.disabled=false;}});
 if(['super_admin','admin','pastor'].includes(profile.role)){
 let permissions=$('exportPermissions');if(!permissions){permissions=document.createElement('div');permissions.id='exportPermissions';$('assignmentPanel').append(permissions);}
 permissions.innerHTML='<h3>Sensitive Excel export access</h3><p>Administrators can export care details. Grant this separately to pastors who need it. Restricted pastoral notes are never exported.</p>'+staff.filter(s=>s.role==='pastor'&&s.is_active).map(s=>`<label class="staff-toggle"><input type="checkbox" data-export="${s.id}" ${s.can_export_sensitive?'checked':''}> ${e(s.name)}</label>`).join('');
 permissions.querySelectorAll('[data-export]').forEach(input=>input.onchange=async()=>{input.disabled=true;const {error}=await supabase.rpc('set_sensitive_export',{p_user:input.dataset.export,p_enabled:input.checked});if(error){input.checked=!input.checked;setMessage($('ministryMessage'),error.message,'error');}input.disabled=false;});
 permissions.insertAdjacentHTML('beforeend','<h3>Operations Admin report approval</h3><p>Super Admins and pastors may approve visitor report downloads for an Operations Admin.</p>'+staff.filter(s=>s.role==='coordinator'&&s.is_active).map(s=>`<label class="staff-toggle"><input type="checkbox" data-report="${s.id}" ${s.can_export_reports?'checked':''}> ${e(s.name)}</label>`).join(''));
 permissions.querySelectorAll('[data-report]').forEach(input=>input.onchange=async()=>{input.disabled=true;const {error}=await supabase.rpc('set_report_export',{p_user:input.dataset.report,p_enabled:input.checked});if(error){input.checked=!input.checked;setMessage($('ministryMessage'),error.message,'error');}input.disabled=false;});
 }
 const scope=$('careScope').value,shown=requests.filter(r=>scope==='all'||(scope==='open'?r.status!=='Responded':r.status===scope)).sort((a,b)=>(a.priority==='Urgent'?-1:1)-(b.priority==='Urgent'?-1:1));
 $('careQueue').innerHTML=shown.map(r=>{const person=people.find(p=>p.person_id===r.person_id);return `<article class="note-item"><h3>${person?link(person):'Visitor'} · ${e(r.priority)} · ${e(r.status)}</h3><p>${e(r.reason)}</p>${leader()?`<form data-care="${r.id}" class="form-grid"><label>Pastor<select name="assigned_to"><option value="">Unassigned</option>${staff.filter(s=>s.role==='pastor'&&s.is_active).map(s=>`<option value="${s.id}" ${s.id===r.assigned_to?'selected':''}>${e(s.name)}</option>`).join('')}</select></label><label>Status<select name="status">${['Open','In progress','Responded'].map(s=>`<option ${r.status===s?'selected':''}>${s}</option>`).join('')}</select></label><label>Response / agreed next step<textarea name="response" maxlength="3000">${e(r.response)}</textarea></label><button class="primary-action">Save care response</button></form>`:`<p>${e(r.response||'Awaiting pastoral response')}</p>`}</article>`;}).join('')||'<p>No requests in this view.</p>';
 $('careQueue').querySelectorAll('form').forEach(form=>form.onsubmit=async event=>{event.preventDefault();event.submitter.disabled=true;try{const values=Object.fromEntries(new FormData(form));values.assigned_to||=null;const {data,error}=await supabase.from('care_requests').update(values).eq('id',form.dataset.care).select('id');if(error)throw error;if(!data.length)throw new Error('Care request was not updated.');dirty=false;await load();setMessage($('ministryMessage'),'Care response saved.','success');}catch(err){setMessage($('ministryMessage'),err.message,'error');}finally{event.submitter.disabled=false;}});
}
async function load(){if(dirty)return;[people,events,staff,requests]=await Promise.all([readAllRows('people_overview'),readAllRows('visitor_events'),readAllRows('users'),readAllRows('care_requests')]);render();}
$('journeyMonth').onchange=render;$('careScope').onchange=render;
$('assignWaiting').onclick=async()=>{$('assignWaiting').disabled=true;try{const {data,error}=await supabase.rpc('assign_waiting_visitors');if(error)throw error;await load();setMessage($('ministryMessage'),data+' visitors assigned.','success');}catch(err){setMessage($('ministryMessage'),err.message,'error');}finally{$('assignWaiting').disabled=false;}};
initProtectedPage({onReady:async context=>{profile=context.profile;await load();subscribeTables(['visitor_events','care_requests','followups','users'],load);}});
