import {supabase} from '../../shared/supabase.js';
import {escapeHtml as e,formatTimestamp,setMessage,subscribeTables} from './auth.js';
export async function setupJourney(personId,profile){
 const leader=['admin','pastor'].includes(profile.role);
 const host=document.createElement('section');host.className='panel';host.innerHTML=`<h2>Care journey & timeline</h2><p>Record actual visit and class dates. Record successful contact separately from an unsuccessful attempt.</p><div id="journeyMessage" class="inline-alert hidden" role="status"></div><form id="eventForm" class="form-grid"><label>Event<select name="kind">${[['first_visit','First visit'],['return_visit','Return visit'],['call','Reached visitor / successful contact'],['call_attempt','Unsuccessful contact attempt'],['next_step','Agreed next step'],['discipleship_started','Started discipleship class'],['discipleship_completed','Completed discipleship class'],['membership_interest','Interested in membership'],['member_joined','Became a member']].map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></label><label>Date<input name="occurred_on" type="date" required></label><label>Outcome / details<textarea name="detail" maxlength="5000"></textarea></label><button class="primary-action">Add to timeline</button></form><h3>Request pastoral attention</h3><form id="careForm" class="form-grid"><label>Priority<select name="priority"><option>Normal</option><option>Urgent</option></select></label><label>Reason<textarea name="reason" required maxlength="3000"></textarea></label><button class="primary-action">Flag for pastor</button></form><p class="muted-text">Requests and responses are visible to assigned follow-up staff and leaders. Contact a pastor directly for immediate attention.</p>${leader?'<h3>Restricted pastoral notes</h3><p>Visible only to pastors and administrators. Excluded from Excel reports.</p><form id="pastoralForm" class="stack-form"><label>Pastoral note<textarea name="note" maxlength="10000" required></textarea></label><button class="primary-action">Save restricted note</button></form><div id="pastoralNotes"></div>':''}<h3>Timeline</h3><div id="journeyTimeline"></div>`;
 document.querySelector('.page-content').append(host);
 const date=host.querySelector('[name="occurred_on"]');date.value=new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Johannesburg',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());date.max=date.value;
 const message=host.querySelector('#journeyMessage');
 async function query(table,order){const {data,error}=await supabase.from(table).select('*, users(name)').eq('person_id',personId).order(order,{ascending:false});if(error)throw error;return data||[];}
 async function refresh(){
  const [events,notes,activity]=await Promise.all([query('visitor_events','occurred_on'),query('followup_notes','created_at'),query('activity_logs','timestamp')]);
  const timeline=[...events.map(x=>({date:x.occurred_on,title:x.kind.replaceAll('_',' ')+' · '+(x.users?.name||'Public visitor intake'),detail:x.detail})),...notes.map(x=>({date:x.created_at,title:'Follow-up note · '+(x.users?.name||'Staff member'),detail:x.note})),...activity.filter(x=>['assignment_changed','followup_updated'].includes(x.action)).map(x=>({date:x.timestamp,title:x.action.replaceAll('_',' '),detail:x.details?.summary||''}))].sort((a,b)=>b.date.localeCompare(a.date));
  host.querySelector('#journeyTimeline').innerHTML=timeline.map(x=>`<article class="note-item"><strong>${e(x.title)}</strong><p class="muted-text">${x.date.length===10?e(x.date):formatTimestamp(x.date)}</p><p>${e(x.detail)}</p></article>`).join('')||'<p>No journey events recorded yet.</p>';
  if(leader){const privateNotes=await query('pastoral_notes','created_at');host.querySelector('#pastoralNotes').innerHTML=privateNotes.map(x=>`<article class="note-item"><span>${formatTimestamp(x.created_at)} · ${e(x.users?.name||"Leader")}</span><p>${e(x.note)}</p></article>`).join('');}
 }
 for(const [id,table] of [['eventForm','visitor_events'],['careForm','care_requests'],['pastoralForm','pastoral_notes']]){
  const form=host.querySelector('#'+id);if(!form)continue;
  form.onsubmit=async event=>{event.preventDefault();event.submitter.disabled=true;try{const values=Object.fromEntries(new FormData(form));const {error}=await supabase.from(table).insert({...values,person_id:personId,created_by:profile.id});if(error)throw error;form.querySelector('textarea').value='';await refresh();setMessage(message,'Saved successfully.','success');}catch(error){setMessage(message,/duplicate key/.test(error.message)?'A visit is already recorded for this date, or a first visit already exists.':error.message,'error');}finally{event.submitter.disabled=false;}};
 }
 await refresh();
 subscribeTables(['visitor_events','pastoral_notes','followup_notes','activity_logs'],refresh);
}
